/*
 * This source file was generated by the Gradle 'init' task
 */
package sample;

import sample.controller.AccountController;
import sample.controller.MainMenuController;
import sample.service.AccountService;
import sample.view.ConsoleView;

public class App {

    public static void main(String[] args) {
        ConsoleView consoleView = new ConsoleView();
        AccountService accountService = AccountService.instance();

        AccountController accountController = new AccountController(consoleView, accountService);
        MainMenuController mainMenuController = new MainMenuController(consoleView, accountController);
        mainMenuController.mainMenu();
    }
}
